export const ADD_ORGANIZATION = 'ADD_ORGANIZATION'
export const REMOVE_ORGANIZATION = 'REMOVE_ORGANIZATION'
export const SET_ORGANIZATIONS = 'SET_ORGANIZATIONS'
export const PUT_ORGANIZATION = 'PUT_ORGANIZATION'
export const PATCH_ORGANIZATION = 'PATCH_ORGANIZATION'

export const ADD_USER = 'ADD_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const SET_USERS = 'SET_USERS'
export const PUT_USER = 'PUT_USER'
export const PATCH_USER = 'PATCH_USER'

export const ADD_EVENT = 'ADD_EVENT'
export const REMOVE_EVENT = 'REMOVE_EVENT'
export const SET_EVENTS = 'SET_EVENTS'
export const PUT_EVENT = 'PUT_EVENT'
export const PATCH_EVENT = 'PATCH_EVENT'

export const ADD_INVENTORY = 'ADD_INVENTORY'
export const REMOVE_INVENTORY = 'REMOVE_INVENTORY'
export const SET_INVENTORY = 'SET_INVENTORY'
export const PUT_INVENTORY = 'PUT_INVENTORY'
export const PATCH_INVENTORY = 'PATCH_INVENTORY'

export const SET_CATEGORIES = 'SET_CATEGORIES'

export const SET_EVENTS_TYPES = 'SET_EVENTS_TYPES'



